version: '3'

services:
  mysql-development:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    restart: 'no'
    
    volumes:
      - db_data:/var/lib/mysql
    
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: testapp

    ports:
      - "3308:3306"

volumes:
  db_data: {}

